before_script:
  - cd /var/www/yktaero-prod/yktaero-web

deploying:
  stage: deploy
  only:
      - deploy
  tags:
      - deploy
      - production
  
  script:
    - git reset --hard
    - git pull origin deploy
    - bash /var/www/yktaero-prod/deploy.sh

