# Generated by Django 3.2.8 on 2021-10-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Tag name', max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time the post was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time the post was last updated')),
                ('publish_date', models.DateTimeField(blank=True, help_text='(optional) If set, when to publish the post', null=True)),
                ('title', models.CharField(help_text='Title of the post', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Slug of the post', null=True, unique=True)),
                ('preview_image', models.TextField(blank=True, help_text='URL of the preview image')),
                ('preview_text', models.TextField(help_text='Short preview text')),
                ('content', models.TextField(help_text='Content of the post')),
                ('tags', models.ManyToManyField(help_text='Tags', to='yktaero.Tag')),
            ],
        ),
    ]
