# Generated by Django 3.2.8 on 2021-10-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yktaero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_image_external',
            field=models.TextField(blank=True, help_text='URL of the preview image (external sites)'),
        ),
    ]
