# Generated by Django 3.2.8 on 2021-10-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yktaero', '0002_post_preview_image_external'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User name', max_length=255)),
                ('email', models.CharField(help_text='User email', max_length=255)),
                ('text', models.CharField(help_text='Feedback text', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Project internal name', max_length=32, unique=True)),
                ('title', models.CharField(help_text='Project title', max_length=255)),
                ('description', models.TextField(help_text='Project description')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item', max_length=255)),
                ('sku', models.CharField(help_text='SKU of the item', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Slug of the item', null=True, unique=True)),
                ('preview_image', models.TextField(blank=True, help_text='URL of the preview image')),
                ('preview_image_external', models.TextField(blank=True, help_text='URL of the preview image (external sites)')),
                ('preview_text', models.TextField(help_text='Short preview text')),
                ('description', models.TextField(help_text='Long item description')),
                ('specifications', models.TextField(help_text='Technical specifications (specifications tab)')),
                ('docs', models.TextField(blank=True, help_text='Links to datasheets and stuff (docs tab)')),
                ('info', models.TextField(blank=True, help_text='Additional information about item (info tab)')),
                ('project', models.ManyToManyField(help_text='Project', to='yktaero.Project')),
            ],
        ),
    ]
