# Generated by Django 3.2.8 on 2021-10-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yktaero', '0003_feedback_item_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='preview_docs',
            field=models.TextField(blank=True, help_text='Preview datasheet link'),
        ),
    ]
