# Generated by Django 3.2.8 on 2021-10-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yktaero', '0005_rename_name_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='code',
            field=models.CharField(default='', help_text='Internal code', max_length=255),
            preserve_default=False,
        ),
    ]
