# Generated by Django 3.2.8 on 2021-10-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yktaero', '0006_feedback_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='code',
            field=models.CharField(blank=True, help_text='Internal code', max_length=255),
        ),
    ]
