# Generated by Django 3.2.8 on 2021-10-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yktaero', '0007_alter_feedback_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(help_text='Feedback text'),
        ),
    ]
