# Generated by Django 3.2.8 on 2021-10-16 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yktaero', '0008_alter_feedback_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date feedback was submitted'),
            preserve_default=False,
        ),
    ]
