# Generated by Django 3.2.8 on 2021-10-19 07:53

from django.db import migrations

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('yktaero', '0009_feedback_created'),
    ]

    operations = []
