# Generated by Django 3.2.8 on 2021-10-19 08:09

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yktaero', '0010_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Content of the post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Preview image'),
        ),
    ]
