# Generated by Django 3.2.8 on 2021-10-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yktaero', '0013_auto_20211019_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_upload',
            field=models.ImageField(blank=True, help_text='Preview image', upload_to=''),
        ),
    ]
