# Generated by Django 3.2.8 on 2021-10-19 08:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yktaero', '0014_alter_post_preview_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Content of the post'),
        ),
    ]
