# Generated by Django 3.2.8 on 2021-10-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yktaero', '0015_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.CharField(blank=True, help_text='URL of the preview image (internal)', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_image_external',
            field=models.CharField(blank=True, help_text='URL of the preview image (external sites)', max_length=255),
        ),
    ]
