# Generated by Django 3.2.8 on 2021-10-19 09:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yktaero', '0016_auto_20211019_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Long item description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='docs',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Links to datasheets and stuff (docs tab)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Additional information about item (info tab)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='specifications',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Technical specifications (specifications tab)'),
        ),
    ]
